/**
 * EventDetail Component Tests
 *
 * Tests rendering, status lifecycle actions (complete, skip, cancel),
 * delete behavior, and not-found state.
 */

import { describe, it, expect, vi, beforeEach, afterAll } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { EventDetail } from '../EventDetail';
import type { PlannerEventWithComputed } from '../../stores/usePlannerStore';

// Mock event factory
function createMockEnrichedEvent(
  overrides: Partial<PlannerEventWithComputed> = {}
): PlannerEventWithComputed {
  const now = new Date();
  return {
    id: 'event-123',
    title: 'Test Sowing Event',
    eventType: 'sow',
    scheduledDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
    status: 'scheduled',
    siteId: 'site-1',
    isAutoGenerated: false,
    createdAt: now,
    updatedAt: now,
    daysUntil: 3,
    isOverdue: false,
    isPending: false,
    displayColor: '#22c55e',
    ...overrides,
  };
}

// Mock store
let mockEvent: PlannerEventWithComputed | undefined;
const mockLoadEvents = vi.fn();
const mockCompleteEvent = vi.fn().mockResolvedValue(undefined);
const mockSkipEvent = vi.fn().mockResolvedValue(undefined);
const mockCancelEvent = vi.fn().mockResolvedValue(undefined);
const mockDeleteEvent = vi.fn().mockResolvedValue(undefined);

vi.mock('../../stores/usePlannerStore', () => ({
  usePlannerStore: () => ({
    isLoading: false,
    loadEvents: mockLoadEvents,
    getEvent: (_id: string) => mockEvent,
    completeEvent: mockCompleteEvent,
    skipEvent: mockSkipEvent,
    cancelEvent: mockCancelEvent,
    deleteEvent: mockDeleteEvent,
  }),
}));

// Mock useParams and navigate
const mockNavigate = vi.fn();
vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    useNavigate: () => mockNavigate,
    useParams: () => ({ id: 'event-123' }),
  };
});

// Mock window.confirm
const originalConfirm = window.confirm;

function renderDetail() {
  return render(
    <MemoryRouter>
      <EventDetail />
    </MemoryRouter>
  );
}

describe('EventDetail', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockEvent = createMockEnrichedEvent();
    window.confirm = vi.fn().mockReturnValue(true);
  });

  afterAll(() => {
    window.confirm = originalConfirm;
  });

  describe('rendering', () => {
    it('renders event title', () => {
      renderDetail();
      expect(screen.getByText('Test Sowing Event')).toBeInTheDocument();
    });

    it('renders event type label', () => {
      renderDetail();
      expect(screen.getByText('Sow')).toBeInTheDocument();
    });

    it('renders status badge', () => {
      renderDetail();
      expect(screen.getByText('Scheduled')).toBeInTheDocument();
    });

    it('renders scheduled date', () => {
      renderDetail();
      expect(screen.getByText('Scheduled Date')).toBeInTheDocument();
    });

    it('renders back navigation button', () => {
      renderDetail();
      const backBtn = screen.getByText(/back to events/i);
      expect(backBtn).toBeInTheDocument();
    });

    it('renders delete button', () => {
      renderDetail();
      expect(screen.getByRole('button', { name: /delete event/i })).toBeInTheDocument();
    });

    it('calls loadEvents on mount', () => {
      renderDetail();
      expect(mockLoadEvents).toHaveBeenCalled();
    });
  });

  describe('not found state', () => {
    it('shows not found message when event does not exist', () => {
      mockEvent = undefined;
      renderDetail();
      expect(screen.getByText('Event not found.')).toBeInTheDocument();
    });

    it('shows link back to event list when not found', () => {
      mockEvent = undefined;
      renderDetail();
      expect(screen.getByText('Back to event list')).toBeInTheDocument();
    });
  });

  describe('status actions for active events', () => {
    it('renders Complete button for scheduled events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();
      expect(screen.getByRole('button', { name: /complete/i })).toBeInTheDocument();
    });

    it('renders Skip button for scheduled events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();
      expect(screen.getByRole('button', { name: /skip/i })).toBeInTheDocument();
    });

    it('renders Cancel Event button for scheduled events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();
      expect(screen.getByRole('button', { name: /cancel event/i })).toBeInTheDocument();
    });

    it('calls completeEvent when Complete is clicked', async () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();

      fireEvent.click(screen.getByRole('button', { name: /complete/i }));

      await waitFor(() => {
        expect(mockCompleteEvent).toHaveBeenCalledWith('event-123');
      });
    });

    it('calls skipEvent when Skip is clicked', async () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();

      fireEvent.click(screen.getByRole('button', { name: /skip/i }));

      await waitFor(() => {
        expect(mockSkipEvent).toHaveBeenCalledWith('event-123');
      });
    });

    it('calls cancelEvent when Cancel Event is clicked', async () => {
      mockEvent = createMockEnrichedEvent({ status: 'scheduled' });
      renderDetail();

      fireEvent.click(screen.getByRole('button', { name: /cancel event/i }));

      await waitFor(() => {
        expect(mockCancelEvent).toHaveBeenCalledWith('event-123');
      });
    });
  });

  describe('terminal status hides actions', () => {
    it('hides lifecycle buttons for completed events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'completed' });
      renderDetail();
      expect(screen.queryByRole('button', { name: /^complete$/i })).not.toBeInTheDocument();
      expect(screen.queryByRole('button', { name: /^skip$/i })).not.toBeInTheDocument();
      expect(screen.queryByRole('button', { name: /cancel event/i })).not.toBeInTheDocument();
    });

    it('hides lifecycle buttons for cancelled events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'cancelled' });
      renderDetail();
      expect(screen.queryByRole('button', { name: /^complete$/i })).not.toBeInTheDocument();
    });

    it('hides lifecycle buttons for skipped events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'skipped' });
      renderDetail();
      expect(screen.queryByRole('button', { name: /^complete$/i })).not.toBeInTheDocument();
    });

    it('still shows delete button for terminal events', () => {
      mockEvent = createMockEnrichedEvent({ status: 'completed' });
      renderDetail();
      expect(screen.getByRole('button', { name: /delete event/i })).toBeInTheDocument();
    });
  });

  describe('delete', () => {
    it('calls deleteEvent and navigates on confirm', async () => {
      renderDetail();

      fireEvent.click(screen.getByRole('button', { name: /delete event/i }));

      await waitFor(() => {
        expect(mockDeleteEvent).toHaveBeenCalledWith('event-123');
        expect(mockNavigate).toHaveBeenCalledWith('/planner/events');
      });
    });

    it('does not delete when confirm is cancelled', async () => {
      window.confirm = vi.fn().mockReturnValue(false);
      renderDetail();

      fireEvent.click(screen.getByRole('button', { name: /delete event/i }));

      await waitFor(() => {
        expect(mockDeleteEvent).not.toHaveBeenCalled();
      });
    });
  });

  describe('overdue display', () => {
    it('shows overdue badge for overdue events', () => {
      mockEvent = createMockEnrichedEvent({
        isOverdue: true,
        status: 'scheduled',
        scheduledDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        daysUntil: -3,
      });
      renderDetail();
      expect(screen.getByText('Overdue')).toBeInTheDocument();
    });

    it('does not show overdue badge for future events', () => {
      mockEvent = createMockEnrichedEvent({ isOverdue: false });
      renderDetail();
      expect(screen.queryByText('Overdue')).not.toBeInTheDocument();
    });
  });

  describe('linked entities', () => {
    it('shows View Tray button when trayId is set', () => {
      mockEvent = createMockEnrichedEvent({ trayId: 'tray-456' });
      renderDetail();
      expect(screen.getByText('View Tray')).toBeInTheDocument();
    });

    it('shows View Batch button when batchId is set', () => {
      mockEvent = createMockEnrichedEvent({ batchId: 'batch-789' });
      renderDetail();
      expect(screen.getByText('View Batch')).toBeInTheDocument();
    });

    it('does not show linked entity section when no links', () => {
      mockEvent = createMockEnrichedEvent({ trayId: undefined, batchId: undefined });
      renderDetail();
      expect(screen.queryByText('View Tray')).not.toBeInTheDocument();
      expect(screen.queryByText('View Batch')).not.toBeInTheDocument();
    });
  });

  describe('metadata', () => {
    it('shows event ID in footer', () => {
      renderDetail();
      expect(screen.getByText(/ID: event-123/)).toBeInTheDocument();
    });

    it('shows auto-generated badge when applicable', () => {
      mockEvent = createMockEnrichedEvent({ isAutoGenerated: true });
      renderDetail();
      expect(screen.getByText('Auto-generated')).toBeInTheDocument();
    });
  });

  describe('navigation', () => {
    it('navigates back to events on back button click', () => {
      renderDetail();
      fireEvent.click(screen.getByText(/back to events/i));
      expect(mockNavigate).toHaveBeenCalledWith('/planner/events');
    });

    it('navigates to tray detail on View Tray click', () => {
      mockEvent = createMockEnrichedEvent({ trayId: 'tray-456' });
      renderDetail();
      fireEvent.click(screen.getByText('View Tray'));
      expect(mockNavigate).toHaveBeenCalledWith('/grow/trays/tray-456');
    });

    it('navigates to batch detail on View Batch click', () => {
      mockEvent = createMockEnrichedEvent({ batchId: 'batch-789' });
      renderDetail();
      fireEvent.click(screen.getByText('View Batch'));
      expect(mockNavigate).toHaveBeenCalledWith('/propagation/batches/batch-789');
    });
  });
});
