/**
 * EventList Component Tests
 *
 * Tests rendering, filtering, empty state, and navigation
 * for the event list view.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { EventList } from '../EventList';
import type { PlannerEventWithComputed } from '../../stores/usePlannerStore';

// Mock event factory
function createMockEnrichedEvent(
  overrides: Partial<PlannerEventWithComputed> = {}
): PlannerEventWithComputed {
  const now = new Date();
  return {
    id: `event-${Math.random().toString(36).slice(2, 9)}`,
    title: 'Test Event',
    eventType: 'sow',
    scheduledDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
    status: 'scheduled',
    siteId: 'site-1',
    isAutoGenerated: false,
    createdAt: now,
    updatedAt: now,
    daysUntil: 7,
    isOverdue: false,
    isPending: false,
    displayColor: '#22c55e',
    ...overrides,
  };
}

// Mock store data
let mockEvents: PlannerEventWithComputed[] = [];
const mockLoadEvents = vi.fn();

vi.mock('../../stores/usePlannerStore', () => ({
  usePlannerStore: () => ({
    events: mockEvents,
    isLoading: false,
    loadEvents: mockLoadEvents,
  }),
}));

// Mock navigate
const mockNavigate = vi.fn();
vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    useNavigate: () => mockNavigate,
  };
});

function renderList() {
  return render(
    <MemoryRouter>
      <EventList />
    </MemoryRouter>
  );
}

describe('EventList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockEvents = [];
  });

  describe('rendering', () => {
    it('renders the page heading', () => {
      renderList();
      expect(screen.getByText('Events')).toBeInTheDocument();
    });

    it('renders the New Event button', () => {
      renderList();
      expect(screen.getByRole('button', { name: /new event/i })).toBeInTheDocument();
    });

    it('renders filter controls', () => {
      renderList();
      expect(screen.getByText('All Types')).toBeInTheDocument();
      expect(screen.getByText('All Statuses')).toBeInTheDocument();
    });

    it('calls loadEvents on mount', () => {
      renderList();
      expect(mockLoadEvents).toHaveBeenCalled();
    });
  });

  describe('empty state', () => {
    it('shows empty message when no events', () => {
      mockEvents = [];
      renderList();
      expect(screen.getByText('No events match your filters.')).toBeInTheDocument();
    });

    it('shows create link in empty state', () => {
      mockEvents = [];
      renderList();
      expect(screen.getByText('Create your first event')).toBeInTheDocument();
    });
  });

  describe('event display', () => {
    it('renders event titles', () => {
      mockEvents = [
        createMockEnrichedEvent({ id: 'e1', title: 'Sow Basil' }),
        createMockEnrichedEvent({ id: 'e2', title: 'Harvest Sunflowers' }),
      ];
      renderList();
      expect(screen.getByText('Sow Basil')).toBeInTheDocument();
      expect(screen.getByText('Harvest Sunflowers')).toBeInTheDocument();
    });

    it('shows event count', () => {
      mockEvents = [
        createMockEnrichedEvent({ id: 'e1' }),
        createMockEnrichedEvent({ id: 'e2' }),
        createMockEnrichedEvent({ id: 'e3' }),
      ];
      renderList();
      expect(screen.getByText('3 events')).toBeInTheDocument();
    });

    it('shows singular "event" for single event', () => {
      mockEvents = [createMockEnrichedEvent({ id: 'e1' })];
      renderList();
      expect(screen.getByText('1 event')).toBeInTheDocument();
    });

    it('shows status badges', () => {
      mockEvents = [
        createMockEnrichedEvent({ id: 'e1', status: 'scheduled' }),
      ];
      renderList();
      // "Scheduled" appears in both filter dropdown and badge; use getAllByText
      const scheduledElements = screen.getAllByText('Scheduled');
      expect(scheduledElements.length).toBeGreaterThanOrEqual(2); // filter option + badge
    });

    it('shows overdue indicator for overdue events', () => {
      mockEvents = [
        createMockEnrichedEvent({
          id: 'e1',
          title: 'Late Task',
          isOverdue: true,
          status: 'scheduled',
          scheduledDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        }),
      ];
      renderList();
      expect(screen.getByText('Overdue')).toBeInTheDocument();
    });
  });

  describe('navigation', () => {
    it('navigates to new event form on New Event click', () => {
      renderList();
      fireEvent.click(screen.getByRole('button', { name: /new event/i }));
      expect(mockNavigate).toHaveBeenCalledWith('/planner/events/new');
    });

    it('navigates to event detail on event row click', () => {
      mockEvents = [
        createMockEnrichedEvent({ id: 'event-abc', title: 'Click Me' }),
      ];
      renderList();
      fireEvent.click(screen.getByText('Click Me'));
      expect(mockNavigate).toHaveBeenCalledWith('/planner/events/event-abc');
    });
  });

  describe('filtering', () => {
    it('filters by event type', () => {
      mockEvents = [
        createMockEnrichedEvent({ id: 'e1', title: 'Sow Task', eventType: 'sow' }),
        createMockEnrichedEvent({ id: 'e2', title: 'Water Task', eventType: 'water' }),
      ];
      renderList();

      // Both should be visible initially
      expect(screen.getByText('Sow Task')).toBeInTheDocument();
      expect(screen.getByText('Water Task')).toBeInTheDocument();
    });

    it('renders all status filter options', () => {
      renderList();
      const statusLabels = ['All Statuses', 'Scheduled', 'Pending', 'Completed', 'Cancelled', 'Skipped'];
      for (const label of statusLabels) {
        expect(screen.getByText(label)).toBeInTheDocument();
      }
    });
  });
});
