/**
 * usePlannerStore - Zustand store for planner event management
 *
 * Manages planner event state in memory with Dexie persistence.
 * Provides computed fields for overdue status, days until, etc.
 *
 * Types, constants, and helpers extracted to usePlannerStore.helpers.ts
 */

import { create } from 'zustand';
import { plannerDb, type PlannerEvent, type PlannerEventType, type PlannerEventStatus } from '@/lib/db';
import {
  enrichEvent,
  isSameDay,
  isWithinRange,
  DEFAULT_FILTERS,
  DEFAULT_SORT,
} from './usePlannerStore.helpers';
import type {
  PlannerEventWithComputed,
  PlannerFilters,
  PlannerSort,
  CreateEventInput,
} from './usePlannerStore.helpers';

// Re-export types for consumers
export type {
  PlannerEventWithComputed,
  PlannerFilters,
  PlannerSort,
  CreateEventInput,
} from './usePlannerStore.helpers';

/**
 * Store state and actions.
 */
export interface PlannerState {
  // Raw data from DB
  rawEvents: PlannerEvent[];
  // Enriched events with computed fields
  events: PlannerEventWithComputed[];
  isLoading: boolean;
  error: string | null;
  filters: PlannerFilters;
  sort: PlannerSort;

  // Actions - CRUD
  loadEvents: () => Promise<void>;
  createEvent: (data: CreateEventInput) => Promise<string>;
  updateEvent: (id: string, updates: Partial<PlannerEvent>) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  getEvent: (id: string) => PlannerEventWithComputed | undefined;

  // Actions - Status Lifecycle
  startEvent: (id: string) => Promise<void>;
  completeEvent: (id: string) => Promise<void>;
  skipEvent: (id: string) => Promise<void>;
  cancelEvent: (id: string) => Promise<void>;

  // Actions - Linking
  linkToTray: (eventId: string, trayId: string) => Promise<void>;
  linkToBatch: (eventId: string, batchId: string) => Promise<void>;
  unlinkEntity: (eventId: string) => Promise<void>;

  // Filters & Sort
  setFilters: (filters: Partial<PlannerFilters>) => void;
  setSort: (sort: PlannerSort) => void;
  resetFilters: () => void;

  // Computed selectors
  getFilteredEvents: () => PlannerEventWithComputed[];
  getEventsByDateRange: (start: Date, end: Date) => PlannerEventWithComputed[];
  getEventsByStatus: (status: PlannerEventStatus) => PlannerEventWithComputed[];
  getEventsBySpecies: (speciesId: string) => PlannerEventWithComputed[];
  getEventsBySite: (siteId: string) => PlannerEventWithComputed[];
  getEventsByTray: (trayId: string) => PlannerEventWithComputed[];
  getEventsByBatch: (batchId: string) => PlannerEventWithComputed[];
  getUpcomingEvents: (days: number) => PlannerEventWithComputed[];
  getOverdueEvents: () => PlannerEventWithComputed[];
  getEventsForDate: (date: Date) => PlannerEventWithComputed[];
  getStatusCounts: () => Record<PlannerEventStatus, number>;
  getEventTypeCounts: () => Record<PlannerEventType, number>;
}

// ============================================
// STORE
// ============================================

export const usePlannerStore = create<PlannerState>((set, get) => ({
  rawEvents: [],
  events: [],
  isLoading: true,
  error: null,
  filters: { ...DEFAULT_FILTERS },
  sort: { ...DEFAULT_SORT },

  loadEvents: async () => {
    try {
      set({ isLoading: true, error: null });
      const rawEvents = await plannerDb.events.toArray();
      const events = rawEvents.map(enrichEvent);
      set({ rawEvents, events, isLoading: false });
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
    }
  },

  createEvent: async (data) => {
    const now = new Date();
    const event: Omit<PlannerEvent, 'id'> = {
      ...data,
      isAutoGenerated: false,
      createdAt: now,
      updatedAt: now,
    };

    try {
      const id = await plannerDb.events.add(event as PlannerEvent);
      const newEvent = { ...event, id: String(id) } as PlannerEvent;
      set((state) => ({
        rawEvents: [...state.rawEvents, newEvent],
        events: [...state.rawEvents, newEvent].map(enrichEvent),
      }));
      return String(id);
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  updateEvent: async (id, updates) => {
    const updatedData = { ...updates, updatedAt: new Date() };

    try {
      await plannerDb.events.update(id, updatedData);
      set((state) => {
        const newRawEvents = state.rawEvents.map((e) =>
          e.id === id ? { ...e, ...updatedData } : e
        );
        return {
          rawEvents: newRawEvents,
          events: newRawEvents.map(enrichEvent),
        };
      });
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  deleteEvent: async (id) => {
    try {
      await plannerDb.events.delete(id);
      set((state) => {
        const newRawEvents = state.rawEvents.filter((e) => e.id !== id);
        return {
          rawEvents: newRawEvents,
          events: newRawEvents.map(enrichEvent),
        };
      });
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  getEvent: (id) => {
    const { events } = get();
    return events.find((e) => e.id === id);
  },

  startEvent: async (id) => {
    await get().updateEvent(id, { status: 'pending' });
  },

  completeEvent: async (id) => {
    await get().updateEvent(id, {
      status: 'completed',
      completedDate: new Date(),
    });
  },

  skipEvent: async (id) => {
    await get().updateEvent(id, { status: 'skipped' });
  },

  cancelEvent: async (id) => {
    await get().updateEvent(id, { status: 'cancelled' });
  },

  linkToTray: async (eventId, trayId) => {
    await get().updateEvent(eventId, {
      trayId,
      batchId: undefined,
    });
  },

  linkToBatch: async (eventId, batchId) => {
    await get().updateEvent(eventId, {
      batchId,
      trayId: undefined,
    });
  },

  unlinkEntity: async (eventId) => {
    await get().updateEvent(eventId, {
      trayId: undefined,
      batchId: undefined,
    });
  },

  setFilters: (filters) => {
    set((state) => ({
      filters: { ...state.filters, ...filters },
    }));
  },

  setSort: (sort) => {
    set({ sort });
  },

  resetFilters: () => {
    set({ filters: { ...DEFAULT_FILTERS } });
  },

  getFilteredEvents: () => {
    const { events, filters, sort } = get();
    let filtered = [...events];

    if (filters.siteId !== 'all') {
      filtered = filtered.filter((e) => e.siteId === filters.siteId);
    }
    if (filters.eventTypes !== 'all') {
      filtered = filtered.filter((e) => filters.eventTypes.includes(e.eventType));
    }
    if (filters.status !== 'all') {
      filtered = filtered.filter((e) => e.status === filters.status);
    }
    if (!filters.showCompleted) {
      filtered = filtered.filter((e) =>
        e.status !== 'completed' && e.status !== 'cancelled' && e.status !== 'skipped'
      );
    }
    if (filters.dateRange) {
      filtered = filtered.filter((e) =>
        isWithinRange(e.scheduledDate, filters.dateRange!.start, filters.dateRange!.end)
      );
    }

    filtered.sort((a, b) => {
      let comparison = 0;
      switch (sort.field) {
        case 'scheduledDate':
          comparison = new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime();
          break;
        case 'title':
          comparison = a.title.localeCompare(b.title);
          break;
        case 'eventType':
          comparison = a.eventType.localeCompare(b.eventType);
          break;
        case 'status':
          comparison = a.status.localeCompare(b.status);
          break;
      }
      return sort.direction === 'asc' ? comparison : -comparison;
    });

    return filtered;
  },

  getEventsByDateRange: (start, end) => {
    const { events } = get();
    return events.filter((e) => isWithinRange(e.scheduledDate, start, end));
  },

  getEventsByStatus: (status) => {
    const { events } = get();
    return events.filter((e) => e.status === status);
  },

  getEventsBySpecies: (speciesId) => {
    const { events } = get();
    return events.filter((e) => e.speciesId === speciesId);
  },

  getEventsBySite: (siteId) => {
    const { events } = get();
    return events.filter((e) => e.siteId === siteId);
  },

  getEventsByTray: (trayId) => {
    const { events } = get();
    return events.filter((e) => e.trayId === trayId);
  },

  getEventsByBatch: (batchId) => {
    const { events } = get();
    return events.filter((e) => e.batchId === batchId);
  },

  getUpcomingEvents: (days) => {
    const { events } = get();
    const today = new Date();
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + days);

    return events
      .filter((e) => {
        if (e.status === 'completed' || e.status === 'cancelled' || e.status === 'skipped') {
          return false;
        }
        return isWithinRange(e.scheduledDate, today, futureDate);
      })
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime());
  },

  getOverdueEvents: () => {
    const { events } = get();
    return events
      .filter((e) => e.isOverdue)
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime());
  },

  getEventsForDate: (date) => {
    const { events } = get();
    return events.filter((e) => isSameDay(e.scheduledDate, date));
  },

  getStatusCounts: () => {
    const { events } = get();
    const counts: Record<PlannerEventStatus, number> = {
      scheduled: 0,
      pending: 0,
      completed: 0,
      cancelled: 0,
      skipped: 0,
    };
    for (const event of events) {
      counts[event.status]++;
    }
    return counts;
  },

  getEventTypeCounts: () => {
    const { events } = get();
    const counts: Record<PlannerEventType, number> = {
      sow: 0, blackout_end: 0, harvest: 0, water: 0,
      inspection: 0, take_cuttings: 0, rooting_check: 0, pot_up: 0,
      harden_off: 0, graduation: 0, maintenance: 0, purchase: 0, other: 0,
    };
    for (const event of events) {
      counts[event.eventType]++;
    }
    return counts;
  },
}));
