/**
 * usePlannerStore - Zustand store for planner event management
 *
 * Manages planner event state in memory with Dexie persistence.
 * Provides computed fields for overdue status, days until, etc.
 *
 * Following patterns from useTrays.ts and useBatches.ts.
 */

import { create } from 'zustand';
import { plannerDb, type PlannerEvent, type PlannerEventType, type PlannerEventStatus } from '@/lib/db';

// ============================================
// TYPES
// ============================================

/**
 * Enriched event with computed fields for UI display.
 */
export interface PlannerEventWithComputed extends PlannerEvent {
  daysUntil: number;
  isOverdue: boolean;
  isPending: boolean;
  displayColor: string;
}

/**
 * Filter state for planner events.
 */
export interface PlannerFilters {
  siteId: string | 'all';
  eventTypes: PlannerEventType[] | 'all';
  status: PlannerEventStatus | 'all';
  showCompleted: boolean;
  dateRange: { start: Date; end: Date } | null;
}

/**
 * Sort configuration.
 */
export interface PlannerSort {
  field: 'scheduledDate' | 'title' | 'eventType' | 'status';
  direction: 'asc' | 'desc';
}

/**
 * Input for creating a new event.
 */
export type CreateEventInput = Omit<PlannerEvent, 'id' | 'createdAt' | 'updatedAt' | 'isAutoGenerated'>;

/**
 * Store state and actions.
 */
export interface PlannerState {
  // Raw data from DB
  rawEvents: PlannerEvent[];
  // Enriched events with computed fields
  events: PlannerEventWithComputed[];
  isLoading: boolean;
  error: string | null;
  filters: PlannerFilters;
  sort: PlannerSort;

  // Actions - CRUD
  loadEvents: () => Promise<void>;
  createEvent: (data: CreateEventInput) => Promise<string>;
  updateEvent: (id: string, updates: Partial<PlannerEvent>) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  getEvent: (id: string) => PlannerEventWithComputed | undefined;

  // Actions - Status Lifecycle
  startEvent: (id: string) => Promise<void>;
  completeEvent: (id: string) => Promise<void>;
  skipEvent: (id: string) => Promise<void>;
  cancelEvent: (id: string) => Promise<void>;

  // Actions - Linking
  linkToTray: (eventId: string, trayId: string) => Promise<void>;
  linkToBatch: (eventId: string, batchId: string) => Promise<void>;
  unlinkEntity: (eventId: string) => Promise<void>;

  // Filters & Sort
  setFilters: (filters: Partial<PlannerFilters>) => void;
  setSort: (sort: PlannerSort) => void;
  resetFilters: () => void;

  // Computed selectors
  getFilteredEvents: () => PlannerEventWithComputed[];
  getEventsByDateRange: (start: Date, end: Date) => PlannerEventWithComputed[];
  getEventsByStatus: (status: PlannerEventStatus) => PlannerEventWithComputed[];
  getEventsBySpecies: (speciesId: string) => PlannerEventWithComputed[];
  getEventsBySite: (siteId: string) => PlannerEventWithComputed[];
  getEventsByTray: (trayId: string) => PlannerEventWithComputed[];
  getEventsByBatch: (batchId: string) => PlannerEventWithComputed[];
  getUpcomingEvents: (days: number) => PlannerEventWithComputed[];
  getOverdueEvents: () => PlannerEventWithComputed[];
  getEventsForDate: (date: Date) => PlannerEventWithComputed[];
  getStatusCounts: () => Record<PlannerEventStatus, number>;
  getEventTypeCounts: () => Record<PlannerEventType, number>;
}

// ============================================
// CONSTANTS
// ============================================

/**
 * Color mapping by event type.
 */
const EVENT_TYPE_COLORS: Record<PlannerEventType, string> = {
  sow: '#22c55e',           // Green
  blackout_end: '#eab308',  // Yellow
  harvest: '#f97316',       // Orange
  water: '#3b82f6',         // Blue
  inspection: '#8b5cf6',    // Violet
  take_cuttings: '#14b8a6', // Teal
  rooting_check: '#06b6d4', // Cyan
  pot_up: '#3b82f6',        // Blue
  harden_off: '#6366f1',    // Indigo
  graduation: '#a855f7',    // Purple
  maintenance: '#6b7280',   // Gray
  purchase: '#ec4899',      // Pink
  other: '#64748b',         // Slate
};

/**
 * Default filter values.
 */
const DEFAULT_FILTERS: PlannerFilters = {
  siteId: 'all',
  eventTypes: 'all',
  status: 'all',
  showCompleted: false,
  dateRange: null,
};

/**
 * Default sort values.
 */
const DEFAULT_SORT: PlannerSort = {
  field: 'scheduledDate',
  direction: 'asc',
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Calculate days until scheduled date.
 * Negative values indicate overdue events.
 */
function calculateDaysUntil(scheduledDate: Date): number {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const scheduled = new Date(scheduledDate);
  const schedDate = new Date(scheduled.getFullYear(), scheduled.getMonth(), scheduled.getDate());
  return Math.floor((schedDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
}

/**
 * Check if event is overdue (past scheduled date and not completed/cancelled/skipped).
 */
function checkIsOverdue(event: PlannerEvent): boolean {
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return false;
  }
  const daysUntil = calculateDaysUntil(event.scheduledDate);
  return daysUntil < 0;
}

/**
 * Check if event is pending (due today).
 */
function checkIsPending(event: PlannerEvent): boolean {
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return false;
  }
  const daysUntil = calculateDaysUntil(event.scheduledDate);
  return daysUntil === 0;
}

/**
 * Get display color for event based on type and status.
 */
function getDisplayColor(event: PlannerEvent): string {
  // Completed/cancelled events are grayed out
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return '#9ca3af'; // Gray-400
  }
  // Overdue events are red-tinted
  if (checkIsOverdue(event)) {
    return '#ef4444'; // Red-500
  }
  return EVENT_TYPE_COLORS[event.eventType] || '#64748b';
}

/**
 * Enrich event with computed fields.
 */
function enrichEvent(event: PlannerEvent): PlannerEventWithComputed {
  return {
    ...event,
    daysUntil: calculateDaysUntil(event.scheduledDate),
    isOverdue: checkIsOverdue(event),
    isPending: checkIsPending(event),
    displayColor: getDisplayColor(event),
  };
}

/**
 * Check if two dates are the same day.
 */
function isSameDay(date1: Date, date2: Date): boolean {
  const d1 = new Date(date1);
  const d2 = new Date(date2);
  return (
    d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate()
  );
}

/**
 * Check if a date is within a range (inclusive).
 */
function isWithinRange(date: Date, start: Date, end: Date): boolean {
  const d = new Date(date).setHours(0, 0, 0, 0);
  const s = new Date(start).setHours(0, 0, 0, 0);
  const e = new Date(end).setHours(23, 59, 59, 999);
  return d >= s && d <= e;
}

// ============================================
// STORE
// ============================================

export const usePlannerStore = create<PlannerState>((set, get) => ({
  rawEvents: [],
  events: [],
  isLoading: true,
  error: null,
  filters: { ...DEFAULT_FILTERS },
  sort: { ...DEFAULT_SORT },

  // Load events from database
  loadEvents: async () => {
    try {
      set({ isLoading: true, error: null });
      const rawEvents = await plannerDb.events.toArray();
      const events = rawEvents.map(enrichEvent);
      set({ rawEvents, events, isLoading: false });
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
    }
  },

  // Create new event
  createEvent: async (data) => {
    const now = new Date();
    const event: Omit<PlannerEvent, 'id'> = {
      ...data,
      isAutoGenerated: false,
      createdAt: now,
      updatedAt: now,
    };

    try {
      const id = await plannerDb.events.add(event as PlannerEvent);
      const newEvent = { ...event, id: String(id) } as PlannerEvent;
      set((state) => ({
        rawEvents: [...state.rawEvents, newEvent],
        events: [...state.rawEvents, newEvent].map(enrichEvent),
      }));
      return String(id);
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  // Update event
  updateEvent: async (id, updates) => {
    const updatedData = { ...updates, updatedAt: new Date() };

    try {
      await plannerDb.events.update(id, updatedData);
      set((state) => {
        const newRawEvents = state.rawEvents.map((e) =>
          e.id === id ? { ...e, ...updatedData } : e
        );
        return {
          rawEvents: newRawEvents,
          events: newRawEvents.map(enrichEvent),
        };
      });
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  // Delete event
  deleteEvent: async (id) => {
    try {
      await plannerDb.events.delete(id);
      set((state) => {
        const newRawEvents = state.rawEvents.filter((e) => e.id !== id);
        return {
          rawEvents: newRawEvents,
          events: newRawEvents.map(enrichEvent),
        };
      });
    } catch (error) {
      set({ error: (error as Error).message });
      throw error;
    }
  },

  // Get event by ID
  getEvent: (id) => {
    const { events } = get();
    return events.find((e) => e.id === id);
  },

  // Status lifecycle: planned/scheduled → pending (in_progress semantics)
  startEvent: async (id) => {
    await get().updateEvent(id, { status: 'pending' });
  },

  // Status lifecycle: → completed
  completeEvent: async (id) => {
    await get().updateEvent(id, {
      status: 'completed',
      completedDate: new Date(),
    });
  },

  // Status lifecycle: → skipped
  skipEvent: async (id) => {
    await get().updateEvent(id, { status: 'skipped' });
  },

  // Status lifecycle: → cancelled
  cancelEvent: async (id) => {
    await get().updateEvent(id, { status: 'cancelled' });
  },

  // Link event to tray
  linkToTray: async (eventId, trayId) => {
    await get().updateEvent(eventId, {
      trayId,
      batchId: undefined, // Clear batch link if any
    });
  },

  // Link event to batch
  linkToBatch: async (eventId, batchId) => {
    await get().updateEvent(eventId, {
      batchId,
      trayId: undefined, // Clear tray link if any
    });
  },

  // Unlink entity
  unlinkEntity: async (eventId) => {
    await get().updateEvent(eventId, {
      trayId: undefined,
      batchId: undefined,
    });
  },

  // Set filters
  setFilters: (filters) => {
    set((state) => ({
      filters: { ...state.filters, ...filters },
    }));
  },

  // Set sort
  setSort: (sort) => {
    set({ sort });
  },

  // Reset filters to defaults
  resetFilters: () => {
    set({ filters: { ...DEFAULT_FILTERS } });
  },

  // Get filtered and sorted events
  getFilteredEvents: () => {
    const { events, filters, sort } = get();

    let filtered = [...events];

    // Apply site filter
    if (filters.siteId !== 'all') {
      filtered = filtered.filter((e) => e.siteId === filters.siteId);
    }

    // Apply event type filter
    if (filters.eventTypes !== 'all') {
      filtered = filtered.filter((e) => filters.eventTypes.includes(e.eventType));
    }

    // Apply status filter
    if (filters.status !== 'all') {
      filtered = filtered.filter((e) => e.status === filters.status);
    }

    // Apply showCompleted filter
    if (!filters.showCompleted) {
      filtered = filtered.filter((e) =>
        e.status !== 'completed' && e.status !== 'cancelled' && e.status !== 'skipped'
      );
    }

    // Apply date range filter
    if (filters.dateRange) {
      filtered = filtered.filter((e) =>
        isWithinRange(e.scheduledDate, filters.dateRange!.start, filters.dateRange!.end)
      );
    }

    // Sort
    filtered.sort((a, b) => {
      let comparison = 0;
      switch (sort.field) {
        case 'scheduledDate':
          comparison = new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime();
          break;
        case 'title':
          comparison = a.title.localeCompare(b.title);
          break;
        case 'eventType':
          comparison = a.eventType.localeCompare(b.eventType);
          break;
        case 'status':
          comparison = a.status.localeCompare(b.status);
          break;
      }
      return sort.direction === 'asc' ? comparison : -comparison;
    });

    return filtered;
  },

  // Get events within date range
  getEventsByDateRange: (start, end) => {
    const { events } = get();
    return events.filter((e) => isWithinRange(e.scheduledDate, start, end));
  },

  // Get events by status
  getEventsByStatus: (status) => {
    const { events } = get();
    return events.filter((e) => e.status === status);
  },

  // Get events by species
  getEventsBySpecies: (speciesId) => {
    const { events } = get();
    return events.filter((e) => e.speciesId === speciesId);
  },

  // Get events by site
  getEventsBySite: (siteId) => {
    const { events } = get();
    return events.filter((e) => e.siteId === siteId);
  },

  // Get events by tray
  getEventsByTray: (trayId) => {
    const { events } = get();
    return events.filter((e) => e.trayId === trayId);
  },

  // Get events by batch
  getEventsByBatch: (batchId) => {
    const { events } = get();
    return events.filter((e) => e.batchId === batchId);
  },

  // Get upcoming events (next N days)
  getUpcomingEvents: (days) => {
    const { events } = get();
    const today = new Date();
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + days);

    return events
      .filter((e) => {
        if (e.status === 'completed' || e.status === 'cancelled' || e.status === 'skipped') {
          return false;
        }
        return isWithinRange(e.scheduledDate, today, futureDate);
      })
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime());
  },

  // Get overdue events
  getOverdueEvents: () => {
    const { events } = get();
    return events
      .filter((e) => e.isOverdue)
      .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime());
  },

  // Get events for a specific date
  getEventsForDate: (date) => {
    const { events } = get();
    return events.filter((e) => isSameDay(e.scheduledDate, date));
  },

  // Get counts by status
  getStatusCounts: () => {
    const { events } = get();
    const counts: Record<PlannerEventStatus, number> = {
      scheduled: 0,
      pending: 0,
      completed: 0,
      cancelled: 0,
      skipped: 0,
    };

    for (const event of events) {
      counts[event.status]++;
    }

    return counts;
  },

  // Get counts by event type
  getEventTypeCounts: () => {
    const { events } = get();
    const counts: Record<PlannerEventType, number> = {
      sow: 0,
      blackout_end: 0,
      harvest: 0,
      water: 0,
      inspection: 0,
      take_cuttings: 0,
      rooting_check: 0,
      pot_up: 0,
      harden_off: 0,
      graduation: 0,
      maintenance: 0,
      purchase: 0,
      other: 0,
    };

    for (const event of events) {
      counts[event.eventType]++;
    }

    return counts;
  },
}));
