/**
 * usePlannerStore - Helper functions, types, and constants
 *
 * Extracted from usePlannerStore.ts for code health.
 * Contains type definitions, color mappings, date helpers,
 * and event enrichment logic.
 */

import type { PlannerEvent, PlannerEventType, PlannerEventStatus } from '@/lib/db';

// ============================================
// TYPES
// ============================================

/**
 * Enriched event with computed fields for UI display.
 */
export interface PlannerEventWithComputed extends PlannerEvent {
  daysUntil: number;
  isOverdue: boolean;
  isPending: boolean;
  displayColor: string;
}

/**
 * Filter state for planner events.
 */
export interface PlannerFilters {
  siteId: string | 'all';
  eventTypes: PlannerEventType[] | 'all';
  status: PlannerEventStatus | 'all';
  showCompleted: boolean;
  dateRange: { start: Date; end: Date } | null;
}

/**
 * Sort configuration.
 */
export interface PlannerSort {
  field: 'scheduledDate' | 'title' | 'eventType' | 'status';
  direction: 'asc' | 'desc';
}

/**
 * Input for creating a new event.
 */
export type CreateEventInput = Omit<PlannerEvent, 'id' | 'createdAt' | 'updatedAt' | 'isAutoGenerated'>;

// ============================================
// CONSTANTS
// ============================================

/**
 * Color mapping by event type.
 */
export const EVENT_TYPE_COLORS: Record<PlannerEventType, string> = {
  sow: '#22c55e',           // Green
  blackout_end: '#eab308',  // Yellow
  harvest: '#f97316',       // Orange
  water: '#3b82f6',         // Blue
  inspection: '#8b5cf6',    // Violet
  take_cuttings: '#14b8a6', // Teal
  rooting_check: '#06b6d4', // Cyan
  pot_up: '#3b82f6',        // Blue
  harden_off: '#6366f1',    // Indigo
  graduation: '#a855f7',    // Purple
  maintenance: '#6b7280',   // Gray
  purchase: '#ec4899',      // Pink
  other: '#64748b',         // Slate
};

/**
 * Default filter values.
 */
export const DEFAULT_FILTERS: PlannerFilters = {
  siteId: 'all',
  eventTypes: 'all',
  status: 'all',
  showCompleted: false,
  dateRange: null,
};

/**
 * Default sort values.
 */
export const DEFAULT_SORT: PlannerSort = {
  field: 'scheduledDate',
  direction: 'asc',
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Calculate days until scheduled date.
 * Negative values indicate overdue events.
 */
export function calculateDaysUntil(scheduledDate: Date): number {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const scheduled = new Date(scheduledDate);
  const schedDate = new Date(scheduled.getFullYear(), scheduled.getMonth(), scheduled.getDate());
  return Math.floor((schedDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
}

/**
 * Check if event is overdue (past scheduled date and not completed/cancelled/skipped).
 */
export function checkIsOverdue(event: PlannerEvent): boolean {
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return false;
  }
  const daysUntil = calculateDaysUntil(event.scheduledDate);
  return daysUntil < 0;
}

/**
 * Check if event is pending (due today).
 */
export function checkIsPending(event: PlannerEvent): boolean {
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return false;
  }
  const daysUntil = calculateDaysUntil(event.scheduledDate);
  return daysUntil === 0;
}

/**
 * Get display color for event based on type and status.
 */
export function getDisplayColor(event: PlannerEvent): string {
  // Completed/cancelled events are grayed out
  if (event.status === 'completed' || event.status === 'cancelled' || event.status === 'skipped') {
    return '#9ca3af'; // Gray-400
  }
  // Overdue events are red-tinted
  if (checkIsOverdue(event)) {
    return '#ef4444'; // Red-500
  }
  return EVENT_TYPE_COLORS[event.eventType] || '#64748b';
}

/**
 * Enrich event with computed fields.
 */
export function enrichEvent(event: PlannerEvent): PlannerEventWithComputed {
  return {
    ...event,
    daysUntil: calculateDaysUntil(event.scheduledDate),
    isOverdue: checkIsOverdue(event),
    isPending: checkIsPending(event),
    displayColor: getDisplayColor(event),
  };
}

/**
 * Check if two dates are the same day.
 */
export function isSameDay(date1: Date, date2: Date): boolean {
  const d1 = new Date(date1);
  const d2 = new Date(date2);
  return (
    d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate()
  );
}

/**
 * Check if a date is within a range (inclusive).
 */
export function isWithinRange(date: Date, start: Date, end: Date): boolean {
  const d = new Date(date).setHours(0, 0, 0, 0);
  const s = new Date(start).setHours(0, 0, 0, 0);
  const e = new Date(end).setHours(23, 59, 59, 999);
  return d >= s && d <= e;
}
