/**
 * Planner Module - Type Definitions
 *
 * Complete TypeScript types for the Paddock Planner module.
 * Enables scheduling, tracking, and managing growing activities
 * across Grow (microgreen) and Propagation modules.
 *
 * From PRD: docs/planner/PRD.md
 */

import type { PlannerEventType } from './eventTypes';

// Re-export for convenience
export type { PlannerEventType };

// ============================================
// EVENT STATUS
// ============================================

/**
 * Status lifecycle for planner events.
 * Events progress through these states as they are worked.
 */
export type PlannerEventStatus =
  | 'scheduled'  // Future event, not yet due
  | 'pending'    // Due today or overdue, needs action
  | 'completed'  // Successfully completed
  | 'cancelled'  // No longer needed, removed from schedule
  | 'skipped';   // Deliberately skipped, not applicable

/**
 * All valid statuses as an array for iteration.
 */
export const ALL_EVENT_STATUSES: PlannerEventStatus[] = [
  'scheduled',
  'pending',
  'completed',
  'cancelled',
  'skipped',
];

/**
 * Statuses that represent active/actionable events.
 */
export const ACTIVE_STATUSES: PlannerEventStatus[] = ['scheduled', 'pending'];

/**
 * Statuses that represent terminal states.
 */
export const TERMINAL_STATUSES: PlannerEventStatus[] = ['completed', 'cancelled', 'skipped'];

/**
 * Check if a status is active (requires action).
 */
export function isActiveStatus(status: PlannerEventStatus): boolean {
  return ACTIVE_STATUSES.includes(status);
}

/**
 * Check if a status is terminal (no further action).
 */
export function isTerminalStatus(status: PlannerEventStatus): boolean {
  return TERMINAL_STATUSES.includes(status);
}

// ============================================
// CORE ENTITIES
// ============================================

/**
 * Core planner event entity.
 * Represents a single scheduled activity in the calendar.
 *
 * Key invariants:
 * - At most one of trayId or batchId can be set (mutual exclusivity)
 * - siteId is always required for location context
 * - isAutoGenerated events are derived from trays/batches
 */
export interface PlannerEvent {
  id?: string;

  // Core Fields
  title: string;
  eventType: PlannerEventType;
  scheduledDate: Date;
  completedDate?: Date;
  status: PlannerEventStatus;

  // Optional Linking (at most one)
  speciesId?: string;          // Link to variety/species config
  trayId?: string;             // Link to GrowTray
  batchId?: string;            // Link to PropBatch

  // Location Context
  siteId: string;              // Required: FK to GrowSite
  stationId?: string;          // Optional: FK to PropStation

  // Additional Data
  notes?: string;

  // Auto-generation tracking
  isAutoGenerated: boolean;
  sourceType?: 'tray' | 'batch';
  sourceId?: string;           // ID of generating entity

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Enriched event with computed fields for UI display.
 * These fields are calculated at runtime, not persisted.
 */
export interface PlannerEventWithComputed extends PlannerEvent {
  daysUntil: number;           // Days until scheduledDate (negative if past)
  isOverdue: boolean;          // Past scheduledDate and not completed
  isPending: boolean;          // Due today
  displayColor: string;        // Based on eventType and status
  linkedEntityName?: string;   // Tray/batch identifier for display
}

// ============================================
// INPUT TYPES
// ============================================

/**
 * Input for creating a new planner event.
 * Omits auto-generated fields.
 */
export type CreateEventInput = Omit<
  PlannerEvent,
  'id' | 'createdAt' | 'updatedAt' | 'isAutoGenerated'
>;

/**
 * Input for updating an existing event.
 * All fields optional except identity.
 */
export type UpdateEventInput = Partial<
  Omit<PlannerEvent, 'id' | 'createdAt' | 'updatedAt'>
>;

/**
 * Input for linking an event to an entity.
 */
export interface LinkEventInput {
  eventId: string;
  trayId?: string;
  batchId?: string;
}

// ============================================
// FILTER & SORT TYPES
// ============================================

/**
 * Filter state for planner events.
 * 'all' means no filter applied for that dimension.
 */
export interface PlannerFilters {
  siteId: string | 'all';
  eventTypes: PlannerEventType[] | 'all';
  status: PlannerEventStatus | 'all';
  showCompleted: boolean;
  dateRange: { start: Date; end: Date } | null;
}

/**
 * Default filter values.
 */
export const DEFAULT_PLANNER_FILTERS: PlannerFilters = {
  siteId: 'all',
  eventTypes: 'all',
  status: 'all',
  showCompleted: false,
  dateRange: null,
};

/**
 * Sort configuration for planner events.
 */
export interface PlannerSort {
  field: 'scheduledDate' | 'title' | 'eventType' | 'status';
  direction: 'asc' | 'desc';
}

/**
 * Default sort values.
 */
export const DEFAULT_PLANNER_SORT: PlannerSort = {
  field: 'scheduledDate',
  direction: 'asc',
};

// ============================================
// AUTO-GENERATION TYPES
// ============================================

/**
 * Source type for auto-generated events.
 */
export type AutoEventSource = 'tray' | 'batch';

/**
 * Configuration for auto-event generation from trays.
 */
export interface TrayAutoEventConfig {
  source: 'tray';
  trayId: string;
  eventType: PlannerEventType;
  scheduledDate: Date;
  title: string;
  siteId: string;
  speciesId?: string;
}

/**
 * Configuration for auto-event generation from batches.
 */
export interface BatchAutoEventConfig {
  source: 'batch';
  batchId: string;
  eventType: PlannerEventType;
  scheduledDate: Date;
  title: string;
  siteId: string;
  stationId?: string;
  speciesId?: string;
}

/**
 * Union of auto-event configurations.
 */
export type AutoEventConfig = TrayAutoEventConfig | BatchAutoEventConfig;

// ============================================
// INTEGRATION TYPES
// ============================================

/**
 * Result of creating an entity from a planner event.
 */
export interface CreateEntityResult {
  success: boolean;
  entityId?: string;
  error?: string;
}

/**
 * Options for creating a tray from an event.
 */
export interface CreateTrayFromEventOptions {
  eventId: string;
  seedWeight: number;
  growingMedium: string;
  preSoaked?: boolean;
  blackoutDays?: number;
}

/**
 * Options for creating a batch from an event.
 */
export interface CreateBatchFromEventOptions {
  eventId: string;
  quantityStarted: number;
  stationId: string;
  method: string;
  motherPlantId?: string;
}

/**
 * Linked entity information for display.
 */
export interface LinkedEntityInfo {
  type: 'tray' | 'batch';
  id: string;
  identifier: string;      // Tray number or batch number
  species?: string;        // Variety/species name
  status?: string;         // Current status
}

/**
 * Related events for a tray or batch.
 */
export interface RelatedEventsResult {
  events: PlannerEventWithComputed[];
  entityType: 'tray' | 'batch';
  entityId: string;
}

// ============================================
// CALENDAR VIEW TYPES
// ============================================

/**
 * Calendar view modes.
 */
export type CalendarView = 'month' | 'week' | 'day' | 'agenda';

/**
 * Date range for calendar queries.
 */
export interface DateRange {
  start: Date;
  end: Date;
}

/**
 * Event grouped by date for agenda view.
 */
export interface EventsByDate {
  date: Date;
  dateString: string;       // ISO date string for grouping
  events: PlannerEventWithComputed[];
  isToday: boolean;
  isPast: boolean;
}

/**
 * Calendar navigation state.
 */
export interface CalendarState {
  currentDate: Date;
  view: CalendarView;
  selectedDate: Date | null;
  selectedEventId: string | null;
}

// ============================================
// ANALYTICS TYPES
// ============================================

/**
 * Event counts by status.
 */
export type StatusCounts = Record<PlannerEventStatus, number>;

/**
 * Event counts by type.
 */
export type TypeCounts = Record<PlannerEventType, number>;

/**
 * Summary analytics for planner events.
 */
export interface PlannerAnalytics {
  totalEvents: number;
  upcomingCount: number;
  overdueCount: number;
  completedThisWeek: number;
  statusCounts: StatusCounts;
  typeCounts: TypeCounts;
  busyDays: { date: Date; count: number }[];
}

// ============================================
// VALIDATION TYPES
// ============================================

/**
 * Validation result for event data.
 */
export interface EventValidationResult {
  isValid: boolean;
  errors: EventValidationError[];
}

/**
 * Individual validation error.
 */
export interface EventValidationError {
  field: keyof PlannerEvent;
  message: string;
  code: string;
}

/**
 * Validation error codes.
 */
export const EVENT_VALIDATION_ERRORS = {
  TITLE_REQUIRED: 'Title is required',
  TITLE_TOO_LONG: 'Title must be 100 characters or less',
  DATE_IN_PAST: 'Scheduled date cannot be more than 1 year in the past',
  SITE_REQUIRED: 'Site is required',
  INVALID_EVENT_TYPE: 'Invalid event type',
  DUAL_LINK: 'Cannot link to both tray and batch',
} as const;

// ============================================
// TYPE GUARDS
// ============================================

/**
 * Check if an object is a PlannerEvent.
 */
export function isPlannerEvent(obj: unknown): obj is PlannerEvent {
  if (!obj || typeof obj !== 'object') return false;
  const event = obj as Partial<PlannerEvent>;
  return (
    typeof event.title === 'string' &&
    typeof event.eventType === 'string' &&
    event.scheduledDate instanceof Date &&
    typeof event.status === 'string' &&
    typeof event.siteId === 'string'
  );
}

/**
 * Check if an event has a linked entity.
 */
export function hasLinkedEntity(event: PlannerEvent): boolean {
  return !!(event.trayId || event.batchId);
}

/**
 * Get the linked entity type if any.
 */
export function getLinkedEntityType(event: PlannerEvent): 'tray' | 'batch' | null {
  if (event.trayId) return 'tray';
  if (event.batchId) return 'batch';
  return null;
}

/**
 * Get the linked entity ID if any.
 */
export function getLinkedEntityId(event: PlannerEvent): string | null {
  return event.trayId || event.batchId || null;
}
