#!/usr/bin/env bash
#
# Paddock - Development Server Startup Script
# Generated by /dev:setup on 2026-01-13
#
# Usage: ./scripts/start-dev.sh [--fresh] [--skip-deps] [--test]
#
# Options:
#   --fresh     Force reinstall dependencies (removes node_modules)
#   --skip-deps Skip dependency installation
#   --test      Run tests instead of dev server
#
# This script is idempotent - safe to run multiple times.
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
FRESH=false
SKIP_DEPS=false
RUN_TESTS=false
for arg in "$@"; do
    case $arg in
        --fresh) FRESH=true ;;
        --skip-deps) SKIP_DEPS=true ;;
        --test) RUN_TESTS=true ;;
        --help|-h)
            echo "Usage: ./scripts/start-dev.sh [--fresh] [--skip-deps] [--test]"
            echo ""
            echo "Options:"
            echo "  --fresh     Force reinstall dependencies"
            echo "  --skip-deps Skip dependency installation"
            echo "  --test      Run tests instead of dev server"
            exit 0
            ;;
    esac
done

echo -e "${BLUE}🌱 Starting Paddock development environment...${NC}"
echo ""

# ============================================================================
# PREREQUISITES CHECK
# ============================================================================

echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js is required but not installed${NC}"
    echo "  Install from: https://nodejs.org/"
    exit 1
fi
NODE_VERSION=$(node -v)
echo -e "${GREEN}✓ Node.js ${NODE_VERSION}${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}✗ npm is required but not installed${NC}"
    exit 1
fi
NPM_VERSION=$(npm -v)
echo -e "${GREEN}✓ npm ${NPM_VERSION}${NC}"

# Check for Playwright browsers (optional, for e2e tests)
if [ "$RUN_TESTS" = true ]; then
    if ! npx playwright --version &> /dev/null 2>&1; then
        echo -e "${YELLOW}⚠ Playwright not installed, will install with dependencies${NC}"
    fi
fi

echo ""

# ============================================================================
# DEPENDENCIES
# ============================================================================

if [ "$SKIP_DEPS" = false ]; then
    if [ "$FRESH" = true ]; then
        echo -e "${YELLOW}Fresh install requested, removing node_modules...${NC}"
        rm -rf node_modules
        rm -f package-lock.json
    fi

    if [ ! -d "node_modules" ]; then
        echo "Installing dependencies..."
        npm install
        echo -e "${GREEN}✓ Dependencies installed${NC}"
    else
        echo -e "${GREEN}✓ Dependencies already installed${NC}"
        echo -e "  ${YELLOW}(Use --fresh to reinstall)${NC}"
    fi
else
    echo -e "${YELLOW}Skipping dependency installation${NC}"
fi

echo ""

# ============================================================================
# ENVIRONMENT SETUP (Optional for this project)
# ============================================================================

if [ -f ".env.example" ] && [ ! -f ".env" ] && [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}⚠ No .env file found${NC}"
    echo "  Environment variables are optional for local development."
    echo "  Copy .env.example to .env.local if needed for:"
    echo "    - Sentry error tracking"
    echo "    - Plausible analytics"
    echo ""
fi

# ============================================================================
# RUN TESTS OR START DEV SERVER
# ============================================================================

if [ "$RUN_TESTS" = true ]; then
    echo "Running tests..."
    echo ""

    # Run unit tests
    echo -e "${BLUE}Running unit tests...${NC}"
    npm run test

    echo ""
    echo -e "${GREEN}✓ Tests completed${NC}"
else
    echo -e "${GREEN}✓ Environment ready!${NC}"
    echo ""
    echo -e "Starting development server..."
    echo -e "→ ${BLUE}http://localhost:5173${NC}"
    echo ""
    echo -e "${YELLOW}Tips:${NC}"
    echo "  • Press 'o' to open in browser"
    echo "  • Press 'q' to quit"
    echo "  • Run 'npm run test:watch' in another terminal for TDD"
    echo ""

    npm run dev
fi
